# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.0a1.dev20+gfeeeb90.d20230608'
__version_tuple__ = version_tuple = (0, 1, 0, 'dev20', 'gfeeeb90.d20230608')
